<main class="container">
	<header class="page-header">
		<h1 role="heading"><span class="glyphicon glyphicon-plus-sign" role="presentation"></span> Adicionar benefício</h1>
	</header>
	<p class="help-block">Todos os campos marcados com * são obrigatórios</p>
	<form class="row" method="post" <?php echo 'role="form"'; ?>>
		<div class="col-md-6">
		<fieldset>
			<legend>Informações gerais</legend>
			<p class="form-group">
				<label class="control-label" for="eventfbid">
	                <?php echo _('Event ID on Facebook'); ?>*
	            </label>
	             <input autocomplete="on" class="form-control" id="eventfbid" name="eventfbid"
	            placeholder="<?php echo _('Event ID on Facebook'); ?>" required="required"
	            title="<?php echo _('Please, type a valid Facebook Event ID.'); ?>" type="text" value="<?php echo isset($_POST['eventfbid']) ? htmlentities($_POST['eventfbid']) : ''; ?>" />
	            <span class="help-block">Acesse a <a href="//facebook.com/armazemdorosario/events/" rel="external" target="_blank">lista de eventos do Armazém</a> para pegar um.</span>
	        </p>
	        <p class="form-group">
	        	<span class="control-label">
	            	Tipo de benefício*
	            </span>
	            <label class="radio" title="<?php echo _('VIP List'); ?>">
	            	<input name="benefit_type" checked="checked" type="radio" value="1" />
	            	Lista VIP
	            </label>
	            <label class="radio" title="<?php echo _('Sweepstake'); ?>">
	            	<input name="benefit_type" type="radio" value="2" />
	            	Sorteio
	            </label>
	        </p>
	    </fieldset>
		<fieldset>
			<legend>Visual</legend>
			<p class="form-group">
				<label class="control-label" for="photo">Imagem de destaque (opcional)</label>
				<input class="form-control" id="photo" name="photo" placeholder="http://" title="Você pode informar uma URL de alguma imagem que represente este benefício" type="url" value="<?php echo isset($_POST['photo']) ? htmlentities($_POST['photo']) : ''; ?>" />
				<span class="help-block">Cole aqui o URL de uma imagem que represente este benefício</span>
			</p>
			<p class="form-group">
	        	<label class="checkbox" for="featured">
	        		<input id="featured" name="featured" title="Destacar este benefício no app" type="checkbox" value="1" />
	        		Destacar este benefício no <abbr class="initialism" title="aplicativo">app</abbr>
	        	</label>
	        </p>
		</fieldset>
		</div>
		<fieldset class="col-md-6">
			<legend>Restrições</legend>
	        <p class="form-group">
	        	<label class="control-label" for="object">
	        		Objeto do benefício:
	        	</label>
	        	<span>
	        		Nome na portaria
	        	</span>
	        </p>
	        <p class="form-group">
	        	<label class="control-label" for="status">
	        		Privacidade/visibilidade
	        	</label>
	        	<label class="radio">
	        		<input id="status-0" name="status" type="radio" value="0" />
	        		Oculto
	        	</label>
	        	<label class="radio">
	        		<input checked="checked" id="status-1" name="status" type="radio" value="1" />
	        		Aberto
	        	</label>
	        	<label class="radio">
	        		<input id="status-2" name="status" type="radio" value="2" />
	        		Fechado
	        	</label>
	        	<label class="radio">
	        		<input id="status-3" name="status" type="radio" value="3" />
	        		De responsabilidade dos promoters
	        	</label>
	        </p>
			<p class="form-group">
	            <label class="control-label" for="max_num_people_chosen">
	            	Número máximo de beneficiados(as)*
	            </label>
	            <input autocomplete="on" class="form-control" id="max_num_people_chosen" min="10" max="200" name="max_num_people_chosen"
	            placeholder="Valores entre 10 e 200" required="required"
	            title="<?php echo _('At least 10 and at most 200. Example: 100'); ?>" type="number" step="1" value="<?php echo isset($_POST['max_num_people_chosen']) ? htmlentities(intval($_POST['max_num_people_chosen'])) : ''; ?>">
	        </p>
	        <p class="form-group">
	            <label class="control-label" for="accepted_gender">Gêneros permitidos</label>
	            <select class="form-control" id="accepted_gender" name="accepted_gender"
	            title="<?php echo _('Please, select an item'); ?>">
	                <option selected="selected" value=""><?php echo _('Men and women'); ?></option>
	                <option value="female"><?php echo _('Only women'); ?></option>
	                <option value="male"><?php echo _('Only men'); ?></option>
	            </select>
	        </p>
	        <p class="form-group">
	        	<label class="control-label" for="expiration_date">
	        		Serão aceitas participações até*
	        	</label>
	        	<input class="form-control" id="expiration_date" lang="pt-br" name="expiration_date" required="required" title="Por favor, defina uma data de expiração para o benefício." type="datetime-local" value="<?php echo isset($_POST['expiration_date']) ? htmlentities($_POST['expiration_date']) : ''; ?>" />
	        </p>
		</fieldset>
		<fieldset class="col-md-12">
			<hr />
			<button class="btn btn-primary" type="submit"
	        onClick="_gaq.push(['_trackEvent', 'add_benefit', 'submit', 'primary']);">
	        	<?php echo _('Add event'); ?>
	        </button>
        </fieldset>
	</form>
</main>