<?php
$benefit_options = $facebook->getCurrentBenefits(1, 3);
if ( count( $benefit_options ) ) {
?>
<form class="well" method="post">
	<h2 class="h4">Adicionar à Lista VIP</h2>
	<p class="form-group col-xs-12 col-sm-6">
    	<label class="control-label" for="eventfbid">Adicionar a qual evento?</label>
		<select class="form-control" id="eventfbid" name="eventfbid">
			<?php foreach ($benefit_options as $benefit_option) {
				$benefit_option_info = $facebook->getEventInfo($benefit_option['eventfbid']);
			?>
			<?php echo '<option value="' . $benefit_option['eventfbid'] . '">'; ?>
				<?php echo date('d\\/m', strtotime($benefit_option_info['start_time'])) . ' ' . $benefit_option_info['name']; ?>
			<?php echo '</option>'; ?>
			<?php } ?>
		</select>
	</p>
    <?php if(!isset($userfbid)) { ?>
	<p><input autocomplete="on" class="form-control typeahead" type="text" id="userfbid" name="userfbid" placeholder="ID do usuário" /></p>
    <?php } else { ?>
	<input type="hidden" id="userfbid" name="userfbid" value="<?php echo htmlentities($userfbid); ?>" />
    <?php } ?>
    
    <?php if($facebook->userIsAdmin()) { ?>
    <p class="form-group col-xs-12 col-sm-6">
	    <label class="control-label" for="chosen_by_fbid">Adicionar usando o nome de...</label>
        <?php $promoters_list = $facebook->getPromoters(); ?>
    	<select class="form-control" id="chosen_by_fbid" name="chosen_by_fbid">
    		<option selected="selected" value="<?php echo htmlentities($userfbid); ?>">O próprio usuário</option>
        	<?php foreach($promoters_list as $promoter) { ?>
        	<option value="<?php echo $promoter['fbid']; ?>">
        		<?php echo $promoter['fbname']; ?>
        	</option>
            <?php } ?>
        </select>
	</p>
    <?php } ?>
    
	<p class="form-group col-xs-12 col-sm-6">
		<input class="btn btn-primary" type="submit" id="add_to_viplist" name="add_to_viplist" value="Adicionar pessoa" />
	</p>
	<div class="clearfix"></div>
</form>
<?php
} else { ?>
<div class="alert alert-info">
<h2>Ainda n&atilde;o lan&ccedil;amos nenhuma Lista VIP</h2>
<p>Por favor, acesse o <b>app</b> novamente em alguns instantes.</p>
</div>
<?php } ?>
<hr />