<?php use armazemapp\FacebookAdapter; ?>
<table class="table table-condensed table-hover">
    <thead>
        <tr>
        	<th class="hidden-xs text-muted" title="N&uacute;mero de ordem">#</th>
            <th class="hidden-xs">
            	<span class="visible-sm">Nome</span>
            	<span class="visible-md">Nome real</span>
            	<span class="visible-lg">Nome verdadeiro</span>
            </th>
            <th>
            	<span class="visible-xs">Face</span>
            	<span class="visible-sm">Perfil</span>
            	<span class="visible-md">Perfil no Face</span>
            	<span class="visible-lg">Perfil no Facebook</span>
            </th>
            <th class="hidden-xs">Identidade</th>
            <?php if(isset($event_related)) { ?>
            	<th>
            		<span class="hidden-xs">Compareceu?</span>
            		<span class="visible-xs">Foi?</span>
            	</th>
                <th>
                	<span class="hidden-xs">Adicionado(a) por <span class="glyphicon glyphicon-info-sign" data-toggle="tooltip" title="Mostra quem adicionou à lista (geralmente um promoter ou a equipe técnica do app)"></span></span>
                    <span class="visible-xs">Por </span>
                </th>
            <?php } ?>
        </tr>
    </thead>
    <tbody>
	<?php
		$counter = 0;
		foreach($users as $user) {
			$counter++;
			$actually_attended = intval($user['actually_attended'])===1;
	?>
		<tr class="<?php echo FacebookAdapter::getTrustLevelCssClass($user['trust_level']); ?>" id="user-<?php echo htmlentities(trim($user['fbid'])); ?>-benefit-<?php echo $benefit_related; ?>">
			<td class="hidden-xs text-muted" valign="top">
            	<a href="#user-<?php echo htmlentities(trim($user['fbid'])); ?>" onclick="prompt('Aperte Ctrl+C e Enter', '<?php echo htmlentities(trim($user['fbid'])); ?>'); _gaq.push(['_trackEvent', 'copy_id', 'click', '<?php echo htmlentities(trim($user['fbid'])); ?>']); return false;"><?php echo $counter; ?></a>
            </td>
            <td class="hidden-xs" valign="top">
				<p>
					<?php
					
					switch(intval($user['access_level'])) {
						case 1: echo '<span class="badge hidden-xs pull-right">Promoter</span>'; break;
						case 2: echo '<span class="badge hidden-xs pull-right">Funcion&aacute;rio</span>'; break;
						case 3: echo '<span class="badge hidden-xs pull-right">Administrador</span>'; break;
						case 4: echo '<span class="badge hidden-xs pull-right">Super Administrador</span>'; break;
						default: echo ''; break;
					}
					?><a href="//app.armazemdorosario.com.br/admin.php?userfbid=<?php echo htmlentities(trim($user['fbid'])); ?>" onClick="_gaq.push(['_trackEvent', 'user_fullname_listing', 'link_click', '<?php echo $user['fbid']; ?>']);" title="Dados cadastrados/atualizados em <?php echo date('d\\/m H\\:i', strtotime(htmlentities($user['timestamp']))); ?>">
						<?php echo FacebookAdapter::formatUserName($user['name']); ?>
					</a>
					<?php if( intval($user['access_level']) > 0 && FacebookAdapter::userAppearsToBeFake($user['trust_level']) ) { ?>
					<span class="label label-danger">
						<span class="glyphicon glyphicon-flag"></span>
						Cadastro suspeito
					</span>
					<?php } else { ?>
					<small class="text-muted unselectable"><?php
						switch($user['fbgender']) {
							case 'female': ?><abbr title="mulher">&#9792;</abbr><?php break;
							case 'male': ?><abbr title="homem">&#9794;</abbr><?php break;
					} ?></small>
					<?php } // end if ?>
				</p>
			</td>
			<td valign="top">
				<?php if($user['private'] == '1') { ?>
					<small class="text-muted" data-toggle="tooltip" title="Esta pessoa entrou no modo privado">
						<span class="glyphicon glyphicon-lock"></span>
						<?php echo htmlentities(trim($user['fbname'])); ?>
					</small>
				<?php } else { ?>
					<a href="//facebook.com/<?php echo $user['fbid']; ?>" onClick=" _gaq.push(['_trackEvent', 'user_fbname_listing', 'link_click', '<?php echo htmlentities(trim($user['fbid'])); ?>']);">
                    	<?php FacebookAdapter::getUserPicture($user['fbid'], $user['fbname'], 20, 'pull-left'); ?> 
						&nbsp;<?php echo htmlentities(trim($user['fbname'])); ?>
					</a>
				<?php } ?>
			</td>
			<td class="hidden-xs" valign="top">
				<?php echo $user['identidade']; ?>
			</td>
			<?php if(isset($event_related)) { ?>
			<td nowrap="nowrap" valign="top">
				<input
					type="checkbox"
					class="js-switch"
					id="actually_attended_<?php echo $user['fbid']; ?>_<?php echo $benefit_related; ?>"
					name="actually_attended_<?php echo $user['fbid']; ?>_<?php echo $benefit_related; ?>"
					data-userfbid="<?php echo $user['fbid']; ?>"
					data-benefitid="<?php echo $benefit_related; ?>"
					data-eventfbid="<?php echo $event_related; ?>"
					title="Por favor, defina se <?php echo htmlentities(trim($user['fbname'])); ?> compareceu a este evento"
					data-checked-by-server="<?php echo ($actually_attended) ? 'true' : 'false'; ?>"
					<?php echo ($actually_attended) ? 'checked="checked"' : ''; ?>
				/>&nbsp;<label
					id="label_actually_attended_<?php echo $user['fbid']; ?>_<?php echo $benefit_related; ?>"
					for="actually_attended_<?php echo $user['fbid']; ?>_<?php echo $benefit_related; ?>">
					<?php echo ($actually_attended) ? 'Sim' : 'Não'; ?>
				</label>
			</td>
            <td>
            <?php if(isset($user['chosen_by_fbid']) && !empty($user['chosen_by_fbid'])) { ?>
            	<a href="/admin.php?userfbid=<?php echo $user['chosen_by_fbid']; ?>" data-toggle="tooltip" title="<?php echo ($user['chosen_by_name']); ?>">
            	<?php $facebook->getUserPicture($user['chosen_by_fbid'], 'Adicionado(a) por ' . $user['chosen_by_name'], 20, 'pull-left'); ?><span class="hidden-xs">&nbsp;<?php echo $user['chosen_by_fbname']; ?></span>
            <?php } ?>
            	</a>
            </td>
			<?php } // end if isset $event_related ?>
		</tr>
	<?php } // end foreach ?>
	</tbody>
</table>