<table class="table">
	<thead class="sr-only">
    	<tr>
        	<th class="hidden-xs col-sm-1"></th>
        	<th class="col-sm-11">Evento</th>
		</tr>
    </thead>
    <tbody>
<?php
foreach ($facebook->getCurrentBenefits(2) as $event) {
$fbevent = $facebook->getEventInfo($event['eventfbid']);	
?>
    	<tr class="<?php
switch(intval($event['status'])) {
	case 0: echo ''; break;
	case 1: echo 'warning'; break;
	case 2: echo 'success'; break;
} ?>">
        	<td class="hidden-xs col-sm-1" style="background-image: url('https://images.weserv.nl/?url=<?php echo str_replace('http://', '', $event['photo']); ?>');">
            	<img class="img-circle lazy pull-right" src="//graph.facebook.com/<?php echo htmlentities( $fbevent['id'] ); ?>/picture?width=64&height=64" height="64" width="64" />
            </td>
        	<td class="col-sm-11">
            	<details>
					<summary>
                    	<span class="h4"><?php echo htmlentities( $fbevent['name'] ); ?></span>
                        <span class="text-muted"><small>Data de início: <?php echo date('d\\/m H\\:i', strtotime($fbevent['start_time'])); ?> | <a href="http://facebook.com/<?php echo htmlentities( $fbevent['id'] ); ?>" onClick="_gaq.push(['_trackEvent', 'event_on_fb', 'click', '<?php echo htmlentities( $fbevent['id'] ); ?>']);">Evento no Facebook</a> | ID do evento: <?php echo htmlentities( $fbevent['id'] ); ?><br /><?php
switch (intval($event['status'])) {
	case 0: echo 'Sorteio encerrado'; break;
	case 1: echo 'Aberto para participação'; break;
	case 2: echo 'Fechado'; break;
}
?>&nbsp;Data do sorteio: <?php echo date('d\\/m H\\:i', strtotime($event['expiration_date'])); ?></small></span>
<span><a data-toggle="tooltip" data-placement="bottom" href="/admin.php?eventfbid=<?php echo htmlentities( $fbevent['id'] ); ?>&amp;benefit=2&amp;set_status=0" class="btn btn-sm btn-default" title="Oculta este sorteio da página principal do app e na administração.">Ocultar sorteio</a></span>
                    </summary>
                    <?php if(intval($event['status'])==2 || intval($event['status'])==0) { ?>
                    <p><a data-toggle="tooltip" data-placement="bottom" href="/winners-list.xls.php?eventfbid=<?php echo htmlentities( $fbevent['id'] ); ?>&amp;benefit=2" class="btn btn-sm btn-default" <?php echo 'download="Sorteio do evento - ' . htmlentities( $fbevent['name'] ) . ' - ' . date('d\\-m', strtotime($fbevent['start_time'])) . '"'; ?> title="Baixe a planilha do Excel com o nome das pessoas sorteadas">Baixar planilha</a></p>
                    <?php } ?>
                    <div class="well">
                    <?php if(intval($event['status'])==2 || intval($event['status'])==0) { ?>
                    <p>Foram sorteadas <?php echo $event['num_people_chosen']; ?> pessoas. <?php echo $event['num_people_claimed']; ?> pessoas concorreram.</p>
                    <?php
                    $users = $facebook->getChosenUsersFor(2, $fbevent['id']);
					$event_related = $fbevent['id'];
					$benefit_related = 2;
					include('views/admin-list-winners.phtml');
					?>
                    <?php } else { ?>
                    <form method="post">
                    	<input id="eventfbid" name="eventfbid" value="<?php echo htmlentities($event['eventfbid']); ?>" type="hidden">
                        <input id="limit" name="limit" value="<?php echo htmlentities($event['max_num_people_chosen']); ?>" type="hidden">
                    	<p class="text-info">Ainda não foi realizado o sorteio. <button class="btn btn-primary" type="submit" onClick="_gaq.push(['_trackEvent', 'draw_now', 'click', '<?php echo htmlentities($event['eventfbid']); ?>']);">Sortear agora</button></p>
                    </form>
                    <?php } ?>
                    </div>
                </details>
            </td>
        </tr>
<?php } ?>
    </tbody>
</table>