<div class="tab-pane active" id="vip-list">
<h3 class="sr-only">Eventos com Lista VIP</h3>
<table class="table">
	<thead class="sr-only">
    	<tr>
        	<th class="hidden-xs col-sm-1"></th>
        	<th class="col-sm-11">Evento</th>
		</tr>
    </thead>
    <tbody>
<?php
foreach ($facebook->getCurrentBenefits(1) as $event) {
$fbevent = $facebook->getEventInfo($event['eventfbid']);
?>
    	<tr class="<?php
switch(intval($event['status'])) {
	case 0: echo ''; break;
	case 1: echo 'warning'; break;
	case 2: echo 'success'; break;
} ?>">
			<td class="hidden-xs col-sm-1" style="background-image: url('https://images.weserv.nl/?url=<?php echo str_replace('http://', '', $event['photo']); ?>');">
				<?php $facebook->getUserPicture($fbevent['id'], $fbevent['name'], 64, 'pull-right') ?>
            </td>
        	<td class="col-sm-11">
            	<div class="col-sm-6">
            		<h1 class="h4"><a onClick="_gaq.push(['_trackEvent', 'event_on_fb', 'click', '<?php echo htmlentities( $fbevent['id'] ); ?>']);" href="http://facebook.com/<?php echo htmlentities( $fbevent['id'] ); ?>" title="Ver evento no Facebook (abre em uma nova aba)" target="_blank" rel="external" data-toggle="tooltip"><?php echo date('d\\/m H\\:i', strtotime($fbevent['start_time'])); ?> &mdash; <?php echo htmlentities( $fbevent['name'] ); ?></a></h1>
                	<p>Esta Lista VIP comporta <?php echo $event['max_num_people_chosen']; ?> <?php echo $facebook->g('mulheres', 'homens', 'pessoas', $event['accepted_gender']); ?> e deve ser fechada até <?php echo date('d\\/m H\\:i', strtotime($event['expiration_date'])); ?>. <span class="glyphicon glyphicon-info-sign" data-toggle="tooltip" title="A entrada de alguém na Lista VIP está sujeita à condição de não ter faltado a eventos nos quais ganhou cortesia, num intervalo de 15 dias"></span></p>
</div>
<div class="col-sm-6">
<h2 class="sr-only">Ações para esta Lista VIP</h2>            
<ul class="list-inline">
<?php if($current_user_is_admin) { ?>
	<li>
    	<a class="btn btn-default btn-sm" href="#" onClick="window.prompt('Aperte Ctrl+C e Enter para copiar o ID do evento', '<?php echo htmlentities( $fbevent['id'] ); ?>'); return false;" title="Copiar ID do evento" data-toggle="tooltip"><span class="glyphicon glyphicon-pencil"></span> Pegar <abbr title="Identificador">ID</abbr></a>
	</li>
    <li>
        <a data-toggle="tooltip" data-placement="bottom" href="/winners-list.xls.php?eventfbid=<?php echo htmlentities( $fbevent['id'] ); ?>&amp;benefit=1" class="btn btn-sm btn-default"
        <?php echo 'download="Sorteio do evento - ' . htmlentities( $fbevent['name'] ) . ' - ' . date('d\\-m', strtotime($fbevent['start_time'])) . '"'; ?> title="Baixe a planilha do Excel com os nomes da Lista VIP"><span class="glyphicon glyphicon-list-alt"></span> Baixar planilha</a>
	</li>
    <li>
    	<a data-toggle="tooltip" data-placement="bottom" href="/admin.php?eventfbid=<?php echo htmlentities( $fbevent['id'] ); ?>&amp;benefit=1&amp;set_status=0" class="btn btn-sm btn-default" title="Oculta esta Lista VIP do app e da administração"><span class="glyphicon glyphicon-eye-close"></span> Ocultar lista</a>
	</li>
<?php } // end if current user is admin ?>
</ul>
</div>
                
<?php if($event['status']==3) { ?>
<div class="col-sm-6">
	<h2>Promoters</h2>
	<p>Cada promoter pode adicionar, no máximo, <?php echo $event['max_num_people_chosen']/12 ?> <?php echo $facebook->g('mulheres', 'homens', 'pessoas', $event['accepted_gender']); ?></p>
	<ul class="list-inline">
	<?php
	$promoters_stats = $facebook->getPromotersStats($event['eventfbid']);
	foreach($promoters_stats as $stat) {
	?>
		<li title="<?php echo $stat['chosen_by_fbname']; ?> cadastrou <?php echo $stat['count']; ?> <?php echo $facebook->g('mulheres', 'homens', 'pessoas', $event['accepted_gender']); ?>" data-toggle="tooltip"><?php $facebook->getUserPicture($stat['chosen_by_fbid'], $stat['chosen_by_fbname'], 24, 'pull-left'); ?> <span class="badge"><?php echo $stat['count']; ?></span></li>
	<?
	}
	?>
	</ul>
    <p><a data-toggle="tooltip" data-placement="bottom" href="/admin.php?eventfbid=<?php echo htmlentities( $fbevent['id'] ); ?>&amp;benefit=1&amp;set_status=2" class="btn btn-sm btn-default" title="Fecha esta lista VIP. Ela ainda pode ser vista, mas nenhuma pessoa pode ser adicionada."> Fechar lista</a></p>
</div>
<?php } ?>
<div class="clearfix"></div>  
            	<details>
					<summary><span class="badge badge-success"><?php echo $event['num_people_claimed']; ?></span> pessoas est&atilde;o na lista.</summary>
                    <div class="well">
<?php
$users = $facebook->getEventAttendees($fbevent['id'], 1);
$event_related = $fbevent['id'];
$benefit_related = 1;
include('views/admin-list-winners.phtml');
?>
                    </div>
                </details>
            </td>
        </tr>
<?php } ?>
    </tbody>
</table>
</div>