<?php $isUserChosen = $facebook->isUserChosen(2, $benefit['eventfbid']) ?>
<article id="event-<?php echo $benefit['eventfbid']; ?>"> <!-- class="col-xs-12 <?php if($benefit['featured']==='1') { ?>col-sm-12<?php } else { ?>col-sm-6<?php } ?>" -->
	<div class="list-group-item <?php if($claimed && $status==1) { ?>strip strip-participating<?php } ?> <?php if($claimed && $status==2 && $isUserChosen != 1) { ?>strip strip-youlose<?php } ?> <?php if($isUserChosen == 1) { ?>alert-success list-group-item-success<?php } ?>">
    	<?php include 'benefit-header.phtml'; ?>
    <p>
        <?php if($status==1) { ?>Sortearemos<?php } elseif($status==2) { ?>Sorteamos<?php } ?>
        <strong><?php echo htmlentities($benefit['max_num_people_chosen']); ?></strong> <?php echo $benefit['max_num_people_chosen'] > 1 ? $benefit['plural_name'] : $benefit['objectname']; ?> para este evento.<br />
    </p>
<?php
$user_granted_permissions = $facebook->checkPermission('publish_stream') && $facebook->checkPermission('rsvp_event');
if(!$user_granted_permissions) { ?>
<p class="text-alert">Antes de participar, libere acesso ao app.</p>
<?php } else { ?>
    <?php switch($status) {
        case 1: ?>
            <?php if($claimed) { ?>
                <p class="alert alert-info">
                	Você está concorrendo a <?php echo $benefit['max_num_people_chosen'] > 1 ? $benefit['plural_name'] : $benefit['objectname']; ?>. Uma vez que o sorteio for feito, avisaremos aqui.
				</p>
            <?php } else { 
		            if($facebook->canClaimBenefits()) {
		            	include 'benefit-2-claim-form.phtml';
		            } else {
		            	?>
		            <p class="alert alert-danger">Voc&ecirc; n&atilde;o poder&aacute; participar deste sorteio porque n&atilde;o compareceu a algum evento no qual ganhou ingresso nos &uacute;ltimos 30 dias.</p>
		            <?php
		            }
            } // end if claimed
		?> 
            <p class="text-info"><?php $facebook->getSweepstakesBenefitTextInfo($num_people_claimed, $claimed, $facebook->canClaimBenefits()); ?></p>
<p><a <?php $router->generateLink('lista.php?eventfbid='.$benefit['eventfbid'].'&benefit=2'); ?> onClick="_gaq.push(['_trackEvent', 'see_whos_on_the_list', 'btn_default_click', '<?php echo $event['eventfbid']; ?>']);" class="btn btn-sm btn-default">
	Veja quem está concorrendo
</a></p>
        <?php break; case 2: ?>
            <p>
                <?php echo _('Giveaway closed.'); ?>
<?php switch($isUserChosen) {
case -1: echo _('You didn\'t participate in it.'); break;
case 0: echo $facebook->g(_('What a pity! You were not drawn. [female]'), _('What a pity! You were not drawn. [male]'), _('What a pity! You were not drawn. [generic]')); break;
case 1: echo '<div class="alert alert-success"><strong>' . $facebook->g(_('You were drawn [female]'), _('You were drawn [male]'), _('You were drawn')) . '! :D Parabéns! \o/ Seu nome já está na portaria!</strong></div>'; break;
} // end switch ?>
            </p>
            <p><a onClick="_gaq.push(['_trackEvent', 'see_whos_on_the_list', 'btn_default_click', '<?php echo $event['eventfbid']; ?>']);" class="btn btn-sm btn-default" href="lista.php?eventfbid=<?php echo $benefit['eventfbid']; ?>&amp;benefit=2">Veja quem participou do sorteio</a></p>
        <?php break; } // end switch ?>
<?php } ?>
    <?php include 'benefit-2-listing-footer.phtml'; ?>
    <div class="clearfix"></div>
    </div><!-- /.list-group-item -->
</article>
<hr />