<form method="post" class="row">
    <input id="eventfbid" name="eventfbid" type="hidden" value="<?php echo $benefit['eventfbid']; ?>" />
	<input type="hidden" id="eventname" name="eventname" value="<?php echo htmlentities($fbevent['name']); ?>" />
	<input type="hidden" name="eventpicture" name="eventpicture" value="//graph.facebook.com/<?php echo $benefit['eventfbid']; ?>/picture?width=206&height=206" />
	<p class="col-xs-12 col-sm-6">
    	<button onClick="_gaq.push(['_trackEvent', 'attend_to_viplist', 'btn_primary_click', '<?php echo $benefit['eventfbid']; ?>']);" class="btn btn-primary btn-lg" id="attendToEventSubmit" name="attendToEventSubmit" type="submit">
			<?php echo _('Entrar na lista'); ?>
        </button>
	</p>
	<p class="col-xs-12 col-sm-6">
        <label data-placement="bottom" data-toggle="tooltip" for="private" title="<?php echo _('If you enable this feature, other users will not see that you are in the VIP list.'); ?>">
        	<input onClick="_gaq.push(['_trackEvent', 'private', 'checkbox_click', '<?php echo $benefit['eventfbid']; ?>']);" id="private" name="private" type="checkbox" />
            <small><?php echo $facebook->g(_('Sneak [female]'), _('Sneak [male]'), _('Sneak [generic]')); ?></small>
        </label>
	</p>
</form>