<?php
flush();
echo ('</div>');
?>
<div <?php echo 'itemprop="offers" itemscope itemtype="https://schema.org/Offer"'; ?>>
<?php
echo '<meta itemprop="price" content="$0.00" /><meta itemprop="priceCurrency" content="BRL" /><link itemprop="availability" href="https://schema.org/InStock" />';
?>
</div>
<div class="clearfix"></div>
<?php echo ('</div>'); ?>
<script data-cfasync="false" src="/vendor/tuupola/jquery_lazyload/jquery.lazyload.min.js"></script>
<script data-cfasync="false" src="/vendor/abpetkov/switchery-master/dist/switchery.min.js"></script>
<script data-cfasync="false" src="/js/typeahead.bundle.js"></script>
<script data-cfasync="false" src="/js/main.js"></script>
</body>
</html>