<?php
use armazemapp\Gender;

$benefits_for_loop = $facebook->getCurrentBenefits(1);

if(!isset($benefits_for_loop) || empty($benefits_for_loop) || count($benefits_for_loop) < 1) {
?>
<div class="alert">
	<h4>Nenhuma Lista VIP por enquanto :(</h4>
    <p>Até o momento, não há nenhuma Lista VIP aberta para participação.</p>
</div>
<?php
}

foreach ($benefits_for_loop as $benefit) {
	$fbevent = $facebook->getEventInfo($benefit['eventfbid']);
	$attended = $facebook->attendedToEvent($benefit['eventfbid'], $current_user);
	$status = intval($benefit['status']);
	$genderCanAttend = $facebook->genderCanAttend($benefit['accepted_gender'], $user['gender']);
	$limit = intval($benefit['max_num_people_chosen']);
	$is_full = ($benefit['num_people_claimed'] >= $benefit['max_num_people_chosen']);
	$is_published = ($status != 0);
	$is_open = ($status == 1);

	if($limit > 0) {
		$percent = intval($benefit['num_people_claimed'])/$limit * 100;
	}
	else {
		$percent = 0;
	}

	if($is_published) {
		include 'views/benefit-1-item.phtml';
	} // end if
} // end foreach