<div class="clearfix"></div>
<?php echo '<main role="main">'; ?>
	<div class="row">
	    <div class="col-sm-6 col-lg-4">
	    	<div class="panel panel-default">
	    		<div class="panel-heading">
		    		<h2 class="panel-title">Sorteios</h2>
		    	</div>
		        <div class="list-group">
				<?php include_once 'views/listagem-de-sorteios.phtml'; ?>
		        </div>
		        <div class="panel-footer">
		        </div>
	        </div>
		</div>
		<div class="col-sm-6 col-lg-4">
			<div class="panel panel-default">
				<div class="panel-heading">
	    			<h2 class="panel-title">Listas VIP</h2>
	    		</div>
	        	<div class="list-group">
					<?php include_once 'views/listagem-de-eventos.phtml'; ?>
	        	</div>
	        	<div class="panel-footer">
	        	</div>
	        </div>
		</div>
		<div class="col-sm-12 col-lg-4">
			<?php include_once 'views/crush-panel.phtml'; ?>
		</div>
		<div class="clearfix"></div>
	</div>
	<div class="clearfix"></div>
<?php echo '</main>'; ?>