<div class="alert alert-warning">
	<h4><?php echo _('It seems that you can not use our app.'); ?> :(</h4>
	<p>
		<?php echo _('Facebook told us that you are not yet of legal age, and minors can not use this app.'); ?>
		<br />
		<?php echo $facebook->g(_("Come back here when you're a big boy."), _("Come back here when you're a big girl."), _("Come back here when you come of age.")); ?> ;)
	</p>
</div>
<script>
_gaq.push(['_trackEvent', 'legal_age_advised', 'load']);
</script>