<div id="the-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" <?php echo 'aria-hidden="true"'; ?> onclick="_gaq.push(['_trackEvent', 'modal_dismiss', 'close_button_click', '<?php echo $_POST['eventfbid']; ?>']);">&times;</button>
        <h4 class="modal-title">Você está participando de um sorteio!</h4>
      </div>
      <img alt="<?php echo $_POST['eventname']; ?>" src="<?php echo $_POST['photo']; ?>" class="img-responsive" />
      <div class="modal-body">
      	<h2>Você está concorrendo a <?php echo $_POST['max_num_people_chosen'] > 1 ? $_POST['plural_name'] : $_POST['objectname']; ?> do evento &quot;<?php echo $_POST['eventname']; ?>&quot;.</h2>
        <h4>Não se esqueça de ler o <a href="http://app.armazemdorosario.com.br/regulamento.php?eventfbid=<?php echo $_POST['eventfbid']; ?>&benefit_type=2" target="_blank" onclick="window.open(this.href, 'regulamento', 'width=600, height=600'); _gaq.push(['_trackEvent', 'modal_rules', 'popup_click', '<?php echo htmlentities($benefit['eventfbid']); ?>']); return false;">regulamento</a> e retornar ao <a href="/">Armazapp</a> na data marcada para conferir se você ganhou.</h4>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal" onclick="_gaq.push(['_trackEvent', 'modal_dismiss', 'ok_default_button_click', '<?php echo $_POST['eventfbid']; ?>']);">OK</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script>
jQuery('#the-modal').modal('show');
_gaq.push(['_trackEvent', 'modal_show', 'load', '<?php echo $_POST['eventfbid']; ?>']);
</script>