<?php
use armazemapp\FacebookAdapter;
if(!isset($user['fbid'])) {
?>
<div class="alert alert-warning">Este usuário não existe em nosso cadastro. <a class="btn btn-link" href="admin.php" title="Voltar ao painel de administração" onClick="_gaq.push(['_trackEvent', 'back', 'btn_link_click', 'to_admin']);"><span class="glyphicon glyphicon-chevron-left"></span>&nbsp;Voltar</a></div>
<?php
}

$can_remove = ($facebook->getUserLevel() === 4);
if(intval($user['trust_level']) === 0 || isset($_GET['force_trust_level_recalc'])) {
	$user['trust_level'] = $facebook->setUserTrustLevel($user['fbid']);
}
$percent = $user['trust_level'];
?>

<?php if($facebook->userAppearsToBeFake($percent) && $facebook->userIsAdmin() && !$facebook->userIsAdmin($userfbid)) { ?>
<form method="post" class="alert alert-danger">
	<div class="container">
        <h3>Detectamos um problema com este cadastro</h3>
        <details>
            <summary class="h4">Veja o que pode ser feito</summary>
            <div class="well">
              <ul class="list-unstyled">
                  <li>Verifique se o nome informado no cadastro condiz com o nome do Facebook</li>
                  <li>Verifique se está utilizando um nome falso ou se o cadastro foi feito utilizando outro perfil pro engano</li>
              </ul>
            </div>
        </details>
        <p><input type="hidden" name="userfbid" id="userfbid" value="<?php echo $userfbid; ?>" /></p>
        <p><button class="btn btn-danger" id="delete" name="delete" type="submit">Remover este usuário</button></p>
    </div>
</form>
<?php } ?>


<div class="container">

<?php if ($facebook->userIsAdmin() && $user['fbid'] != $current_user['fbid']) { ?>
	<header class="page-header">
	    <hgroup class="col-md-6">
			<h1>
				<a href="http://facebook.com/<?php echo $userfbid; ?>" rel="external" target="_blank">
					<?php FacebookAdapter::getUserPicture($userfbid, $user['fbname'], 100, 'pull-left'); ?>
					<?php echo $facebook->formatUserName($user['fbname']); ?>
				</a>
				<br />
				<small><?php echo $facebook->formatUserName($user['name']); ?></small>
			</h1>
		</hgroup>
		<p>Cadastro feito/atualizado em <?php echo date('d\\/m H\\:i', strtotime(htmlentities($user['timestamp']))); ?></p>
		<div class="col-md-6">
	        <h3>
	        	Confiabilidade:
	        	<a href="?force_trust_level_recalc&amp;userfbid=<?php echo $userfbid; ?>" class="label label-<?php echo $facebook->getTrustLevelCssClass($percent); ?>" data-toggle="tooltip" title="<?php echo $facebook->getTrustLevelExplanation($percent); ?>. Clique ou toque para recalcular.">
	        		<?php echo $percent; ?>%
	        	</a>
	        </h3>
	        <div class="progress">
				<div class="progress-bar progress-bar-<?php echo $facebook->getTrustLevelCssClass($percent); ?>" <?php echo 'role="progressbar" aria-valuenow="' . $percent . '" aria-valuemin="0" aria-valuemax="100"'; ?> style="width: <?php echo $percent; ?>%;">
					<span class="sr-only"><?php echo $percent; ?>% Complete</span>
				</div>
			</div>          
		</div>
		<div class="clear clearfix"></div>
	</header>
<?php } ?>

<?php if($facebook->userIsPromoter() || $facebook->userIsAdmin()) { 
include 'views/add-someone-to-viplist.phtml';
 } ?>

<h3>Registro de atividades</h3>
<p><?php
$user_recent_fails = 0;
$can_claim = $facebook->canClaimBenefits($user['fbid'], $user_recent_fails);

switch($user_recent_fails) {
	case 0:	echo 'Nenhuma ausência';	break;
	case 1:	echo 'Uma ausência';		break;
	default: echo $user_fails . ' ausências'; break;
}?> nos últimos 15 dias.</p>
    <div>
    <table class="table table-condensed table-hover">
    	<thead>
        	<tr>
            	<th>Evento</th>
                <th>Status</th>
              	<th>Foi? <span class="glyphicon glyphicon-info-sign" data-toggle="tooltip" title="Mostra se você realmente compareceu ao evento quando foi sorteado(a) ou participou de Lista VIP."></span></th>
                <th><span class="sr-only">Ações</span></th>
                <th></th>
			</tr>
		</thead>
        <tbody>
<?php
foreach ($user_events as $event) {
	extract($event);
	$fbevent = $facebook->getEventInfo($eventfbid);
	$benefit = intval($benefit);
	$chosen = intval($chosen) === 1;
	$private = intval($private) === 1;
	$status = intval($status);
	$actually_attended = intval($actually_attended);
?>
<tr class="<?php if($actually_attended=='0') { ?>danger<?php } else { echo $chosen || ($benefit_type == 1 && $actually_attended == 1) ? 'success' : ''; } ?> <?php if($status==1 && $benefit_type=2) { echo 'warning'; }?>">
            	<td>
            	<span class="label label-default"><?php if($benefit === 1) { echo 'Lista VIP'; } elseif( $benefit === 2 ) { echo 'Sorteio'; } else { echo ''; } ?></span>
            	<time><?php echo date('d\\/m H\\:i', strtotime($fbevent['start_time'])); ?></time> - <?php echo $fbevent['name']; ?> <span class="label label-default"><?php echo $private ? '<span class="glyphicon glyphicon-lock"></span>&nbsp;Privado' : ''; ?></span></td>
                <td>
<?php
switch($benefit) {
	case 1:
		echo '<span class="label label-success">Entrou na lista</span>';
	break;
	case 2:
		$sorteadx = $facebook->g('Sorteada', 'Sorteado', 'Sorteado(a)', $user['fbgender']);
		$nao_sorteadx = $facebook->g('Não sorteada', 'Não sorteado', 'Não sorteado(a)', $user['fbgender']);
		
		if($status==1) {
			echo '<label class="label label-warning">Aguardando</label>';
		}
		else {
			echo $chosen ? '<span class="label label-success">'.$sorteadx.'</span>' : $nao_sorteadx;
		}
	break;
}
?></td>
			<td>
<?php
if($status!=0) {
	echo 'Ainda não lançado';
}
else {
	switch($benefit) {
		case 1:
			echo ($actually_attended=='0') ? '<strong>Não</strong>' : 'Sim';
		break;
		case 2:
			echo ($chosen) ? (($actually_attended=='0') ? '<strong>Não</strong>' : 'Sim') : '&mdash;';
		break;
	} // end switch
} // end if
?>
            </td>
<?php if ($can_remove && $status!=0) { ?>
			<td>
                <form method="post">
                    <input type="hidden" name="eventfbid" id="eventfbid" value="<?php echo $eventfbid; ?>">
                    <input type="hidden" name="userfbid" id="userfbid" value="<?php echo $userfbid; ?>">
                    <input type="hidden" name="benefit" id="benefit" value="<?php echo $benefit; ?>">
                    <button onClick="_gaq.push(['_trackEvent', 'delete', 'btn_danger', '<?php echo $eventfbid; ?>_<?php echo $userfbid; ?>']);" class="btn btn-danger btn-sm" name="delete" id="delete" value="delete">
                        <span class="glyphicon glyphicon-remove"></span>
                        Remover
                    </button>
                </form>
			</td>
<?php } ?>
            	<td>
            	<?php if (isset($chosen_by_fbid)) { $facebook->getUserPicture($chosen_by_fbid, $chosen_by_fbid, 24); } ?>
                </td>
		</tr>
<?php } // end foreach ?>
	</tbody>
</table>
    </div>
</div>