<?php
$invalid_users = $facebook->getInvalidUsers();
if(count($invalid_users) > 0) {
?>
<div class="panel panel-danger">
	<div class="panel-heading">
		<span class="label label-danger">
			<?php echo $facebook->getInvalidUsersNumber(); ?>
		</span> usuários com problema
	</div>
	<ul class="list-group">
<?php
	foreach($invalid_users as $invalid_user) {
?>
	<li class="list-group-item">
		<a href="/admin.php?userfbid=<?php echo $invalid_user['fbid']; ?>" onClick="_gaq.push(['_trackEvent', 'navbar_trouble_users', 'link_click', '<?php echo $invalid_user['fbid']; ?>']);" title="<?php echo htmlentities(trim($invalid_user['fbname'])); ?>">
			<span class="pull-left"><?php $facebook->getUserPicture($invalid_user['fbid'], $invalid_user['name'], 16); ?></span>
			&nbsp;
			<strong><?php echo htmlentities(trim($invalid_user['name'])); ?></strong>
			<span class="clearfix"></span>
		</a>
	</li>
<?php
	} // end foreach
?>
	</ul><!-- /.list-group -->
<?php } // endif ?>
</div>